# 配置文件

# 本服务参数
wechat:
  ferry:
    # DLL文件位置
    dll-path: E:\WeChatFerry\clients\java\wcf-bmc\dll\sdk.dll
    # socket端口
    socket-port: 10086
    # SDK是否调试模式
    sdk-debug-switch: false
    # 文件下载保存位置
    file-save-path: E:\WeChatFerry\clients\java\wcf-bmc
    # 联系人类型-官方杂号，禁止与其他分类重复(格式：代码|名称)
    contacts-type-mixed:
      - filehelper|文件传输助手
    # 联系人类型-公众号，禁止与其他分类重复(格式：代码|名称)
    contacts-type-official:
      - weixinguanhaozhushou|微信公众平台
    # 接收消息回调开关
    open-msg-group-switch: false
    # 需要开启消息处理的群
    open-msg-groups:
      # key:"[群编号]" val:开启的功能号,对应ReceiveMsgChannelEnum枚举中的code
      "[ALL]": ''
      "[53257911730@chatroom]": '1,2,3'
      "[50501762866@chatroom]": '1'
    # 接收消息回调开关
    receive-msg-callback-switch: false
    # 接收消息回调地址
    receive-msg-callback-urls:
      - http://localhost:9001/msg
    # 发送消息回调标识 1-关闭 2-全部回调 3-发送成功才回调
    send-msg-callback-flag: '1'
    # 发送消息回调地址
    send-msg-callback-urls:
      - http://localhost:9001/msg
    # 调用第三方服务客户端成功状态码
    third-party-ok-codes:
      # key:状态码字段 val:状态码值
      code: '200'

